catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.2.8
  vite-plus: 0.2.8
minimumReleaseAgeExclude:
  - "@solidjs/signals@2.0.0-rc.2"
  - "@solidjs/web@2.0.0-rc.2"
  - solid-js@2.0.0-rc.2
overrides:
  vite: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
